### ISSUE TITLE
Markbot issues I can not figure out how to resolve

### ISSUE THREAD

**Issue by DDesousa0517** [DDesousa0517/html-validation-fixes#1]
Markbot is saying my code has the following issues:

[ ] images/air dino.jpg: Doesn't follow naming conventions
[ ] Your website is not online

I can't figure out how to correct them.
@thomasjbradley

Thank you,
Darice

**Comment by thomasjbradley** [comment]
Re: the image—

What's wrong with the file name? Is there something about the filename that doesn't follow our naming conventions? And it needs to be changed in two places: in the code & in Finder.

---

Re: "not online"—

If you go to the repo page on GitHub.com you'll see that the `Index.html` is misspelled. I know you probably fixed it on your computer, but MacOS will not detect filename changes from upper to lower case.

To fix you'll have to:

1. On your computer: completely rename index to something different like `dino.html`
2. Commit this change in the GitHub app.
3. Rename it back to `index.html`
4. Commit this change in the GitHub app.

Then it should work within a few minutes.

**Comment by DDesousa0517** [comment]
Hi Thomas,

So I did change the file name in the code but I am having a hard time trying to figure out how to change it in the finder ☹ I will keep working on it and see if I can figure it out.

Thanks,
Darcie
